micronaut.application.name=moedaestudantil
datasources.default.db-type=postgres
datasources.default.dialect=POSTGRES
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.url=jdbc:postgresql://localhost:5432/moedaestudantil
datasources.default.username=postgres
datasources.default.password=postgres
jpa.default.properties.hibernate.hbm2ddl.auto=update
#Mostrar os comandos SQL no console
jpa.default.properties.hibernate.show_sql=true
micronaut.server.cors.enabled=true